console.log("Hello from Vue app!")
console.log(Vue)
console.log(typeof(Vue))
console.log(Vue instanceof Object)
console.log(Vue.createApp())
console.log(Vue.createApp())
console.log(Vue.createApp() instanceof Object)
console.log(typeof(Vue.createApp()))
console.log(Vue.createApp)
console.log(typeof(Vue.createApp))
console.log(Vue.createApp instanceof Function)

// const app = Vue.createApp() //TypeError: Cannot read properties of undefined (reading 'render')
// app.mount('#app')